version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      production-gems:
        dependency-type: production
        update-types: [minor, patch]
      development-gems:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      workflow-actions:
        patterns: ["*"]
