require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "config/**/*"

Layout/LineLength:
  Max: 150

Rails/I18nLocaleTexts:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
