inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  Exclude:
    - "db/schema.rb"
    - "db/*_schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
