service: lexaggr

image: jouleka/lexaggr

servers:
  web:
    hosts:
      - YOUR_SERVER_IP
    labels:
      traefik.http.routers.lexaggr.rule: Host(`lexaggr.example.com`)

proxy:
  ssl: true
  host: lexaggr.example.com

registry:
  server: ghcr.io
  username: jouleka
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_LOG_LEVEL: info
    SOLID_QUEUE_IN_PUMA: true
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "lexaggr_storage:/rails/storage"

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:16@sha256:e17e86066e5ef83e0952a9347f5c792b7ece00972e2aa787a6986f471b3dd3d5
    host: YOUR_SERVER_IP
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_DB: lexaggr_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
