production:
  eurlex_rss_sync:
    class: EurlexRssSyncJob
    schedule: "every 2 hours"
  eurlex_sparql_sync:
    class: JurisdictionSyncJob
    args: ["eu"]
    schedule: "every 6 hours"

development:
  eurlex_rss_sync:
    class: EurlexRssSyncJob
    schedule: "every 2 hours"
  eurlex_sparql_sync:
    class: JurisdictionSyncJob
    args: ["eu"]
    schedule: "every 6 hours"
